namespace SnapCd.Common.Dto.Stacks;

/// <summary>
/// DTO for creating a new Stack (POST operations).
/// Does not include Id as it will be generated by the system.
/// </summary>
public class StackCreateDto
{
    public string Name { get; set; } = null!;

    public StackTriggerBehaviour? TriggerBehaviourOnModified { get; set; }
}
